#!/usr/bin/python
# -*- coding: utf-8 -*-

data_dict = {"2": {"key": "1", "qwer": "1", "raw": 0, "column": 1},
             "3": {"key": "2", "qwer": "2", "raw": 0, "column": 2},
             "4": {"key": "3", "qwer": "3", "raw": 0, "column": 3},
             "5": {"key": "4", "qwer": "4", "raw": 0, "column": 4},
             "6": {"key": "5", "qwer": "5", "raw": 0, "column": 5},
             "7": {"key": "6", "qwer": "6", "raw": 0, "column": 6},
             "8": {"key": "7", "qwer": "7", "raw": 0, "column": 7},
             "9": {"key": "8", "qwer": "8", "raw": 0, "column": 8},
             "10": {"key": "9", "qwer": "9", "raw": 0, "column": 9},
             "11": {"key": "0", "qwer": "0", "raw": 0, "column": 10},
             "12": {"key": "*", "qwer": "-", "raw": 0, "column": 11},
             "13": {"key": "=", "qwer": "=", "raw": 0, "column": 12},
             "14": {"key": "ф", "qwer": "", "raw": 0, "column": 0},
             "15": {"key": "ы", "qwer": "", "raw": 0, "column": 0},
             "16": {"key": "а", "qwer": "й", "raw": 1, "column": 1},
             "17": {"key": "я", "qwer": "ц", "raw": 1, "column": 2},
             "18": {"key": "ъ", "qwer": "у", "raw": 1, "column": 3},
             "19": {"key": "й", "qwer": "к", "raw": 1, "column": 4},
             "20": {"key": "м", "qwer": "е", "raw": 1, "column": 5},
             "21": {"key": "р", "qwer": "н", "raw": 1, "column": 6},
             "22": {"key": "п", "qwer": "г", "raw": 1, "column": 7},
             "23": {"key": "х", "qwer": "ш", "raw": 1, "column": 8},
             "24": {"key": "ц", "qwer": "щ", "raw": 1, "column": 9},
             "25": {"key": "щ", "qwer": "з", "raw": 1, "column": 10},
             "26": {"key": ".", "qwer": "х", "raw": 1, "column": 11},
             "27": {"key": ",", "qwer": "ъ", "raw": 1, "column": 12},
             "28": {"key": "ш", "qwer": "", "raw": 0, "column": 0},
             "29": {"key": "", "qwer": ",", "raw": 0, "column": 0},
             "30": {"key": "г", "qwer": "ф", "raw": 2, "column": 1},
             "31": {"key": "и", "qwer": "ы", "raw": 2, "column": 2},
             "32": {"key": "е", "qwer": "в", "raw": 2, "column": 3},
             "33": {"key": "о", "qwer": "а", "raw": 2, "column": 4},
             "34": {"key": "у", "qwer": "п", "raw": 2, "column": 5},
             "35": {"key": "л", "qwer": "р", "raw": 2, "column": 6},
             "36": {"key": "т", "qwer": "о", "raw": 2, "column": 7},
             "37": {"key": "с", "qwer": "л", "raw": 2, "column": 8},
             "38": {"key": "н", "qwer": "д", "raw": 2, "column": 9},
             "39": {"key": "з", "qwer": "ж", "raw": 2, "column": 10},
             "40": {"key": "ж", "qwer": "э", "raw": 2, "column": 11},
             "41": {"key": "ё", "qwer": "ё", "raw": 0, "column": 0},
             "42": {"key": "", "qwer": "", "raw": 0, "column": 0},
             "43": {"key": "", "qwer": "", "raw": 0, "column": 0},
             "44": {"key": "щ", "qwer": "я", "raw": 3, "column": 1},
             "45": {"key": "ь", "qwer": "ч", "raw": 3, "column": 2},
             "46": {"key": "ю", "qwer": "с", "raw": 3, "column": 3},
             "47": {"key": "ъ", "qwer": "м", "raw": 3, "column": 4},
             "48": {"key": "э", "qwer": "и", "raw": 3, "column": 5},
             "49": {"key": "б", "qwer": "т", "raw": 3, "column": 6},
             "50": {"key": "д", "qwer": "ь", "raw": 3, "column": 7},
             "51": {"key": "в", "qwer": "б", "raw": 3, "column": 8},
             "52": {"key": "к", "qwer": "ю", "raw": 3, "column": 9},
             "53": {"key": "ч", "qwer": ".", "raw": 3, "column": 10},
             "54": {"key": "", "qwer": "", "raw": 3, "column": 10},
             "55": {"key": "", "qwer": "", "raw": 0, "column": 0},
             "56": {"key": "", "qwer": "", "raw": 0, "column": 0},
             "57": {"key": " ", "qwer": " ", "raw": 0, "column": 0},
             "58": {"key": "", "qwer": "", "raw": 0, "column": 0}}

counter_fingers = {'f5l': 0, 'f4l': 0, 'f3l': 0, 'f2l': 0, 'f1l': 0, 'f1r': 0, 'f2r': 0, 'f3r': 0, 'f4r': 0, 'f5r': 0}
counter_fingers_qwer = {'f5l': 0, 'f4l': 0, 'f3l': 0, 'f2l': 0, 'f1l': 0, 'f1r': 0, 'f2r': 0, 'f3r': 0, 'f4r': 0,
                        'f5r': 0}